language: node_js
node_js: '6'
before_install:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
deploy:
  provider: npm
  email: scibor.rudnicki@wwwdev.io
  on:
    tags: true
    repo: ngx-prism/core