language: node_js
node_js: '6'
before_install:
- echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
deploy:
  provider: npm
  email: scibor.rudnicki@wwwdev.io
  api_key:
    secure: S5nZIFHPb10j23Hw8WqwCKT7G6k5sI163Vd94FIycBEPzoDBr0QpxORR+R05sPgnFpFzUoJ9xbl0UDZR9gWJXAczR83xqYEqTvqyWv4jGeoxSjQVnOOxNeoqQ/YF7CTTZlgx9I4NfHu8fnXb2//ZRslFdUTA/OoMZ1/aRlmbyC6NAbG+epjrLfU1lV2ICG8b4WWN2ImUC7X+1cem9zE+gr7Q2b/LkxOYYxOiAgUg40A8evA+Ol/H5r6hwANMh6ZOnJmr3fB2W9UREqNRwgqYDdXoD1Ds//wmdiASzKqd+jDfsFxPlmrMPg6g5LhjFPeWEyysZna1qmnfV88DWQTA4fdIoY+fL2tf463U9J7KntGEXeBD/JIGmeawb5vYS5hjnB9a3DXWe2c3TYFfHo6zBwIfy9KsJ4nUjk9mjAzBudKsam4Mx86DudqfyNoff5TCmkbvkS+Lg6DAeR8VeR1xTKeiFLEs+S5ja13xCae+g86bGgq4t04jz6YO47q7h9YTGXiku/xkFGUGWskzdGI5pWCAiPdEC9615FxaztHXAcQQjht6lHW8EnRlbB4f7tMNbjHFo/enUybIR9XWsEJy2NN+zA8uGYk/zue9hleCUJrj9Bk6cSwP5hxQMqI2Bzjjqznw0K6MpVgWb5jztMnLV60laTfSMnJYGsrzoAEb4S8=
  on:
    tags: true
    repo: ngx-prism/core
