language: node_js
node_js: '6'
before_install:
- npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
deploy:
  provider: npm
  email: scibor.rudnicki@wwwdev.io
  skip_cleanp: true
  api_key: $NPM_TOKEN
  on:
    branch: master
    tags: false
    repo: ngx-prism/core
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3