language: node_js
node_js: '6'
before_install:
- npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
deploy:
  provider: npm
  email: scibor.rudnicki@wwwdev.io
  skip_cleanp: true
  on:
    branch: master
    tags: true
    repo: ngx-prism/core
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
dd:
  secure: eVebshxjsjbB3WDmRxXswSDyj1XcVoe7Nn8tA9cgIAZFrw+RbmPi6yss7b0jdZfhvfg8hHIMiFNWfoaGRbilLuFw52HpWbkkXhnBX/Mxb7b4la0GTK0SzfcvkgP/szW2YIL/W7xhdPKNDvL0qFM1XfXw2qNtkqeuoQOlXWgSGd5EuCVj4JLPfbR7nWAbDJvnRgylWEs6Czp3S5QwxCsmBXjWxK0p2KVGcZUkTDQUTjFKyb0h+aYZNJR9fEbcZtoJItD8pg7XL2wDnizcUsmW6+kY7rmbxiwPJXeoFEg+IylNGB3ndBWI/YLUMvj6SLeHN0kOtWEgUfsUKXLcefEE+T9L3rayeE+/qU1pTHSgSFBJX/JgXHCEBcnOypHucgJ8xjIK42Xe+N9LVm3/o1RvDUtTS+Yd1WSBmyhxmS/9pT09OZf6QO5qWpi7J/0rDifCjEHJyTRbT/SNPDsb/LF7TDxmNelvoSWrnUw0eBbJjE8rjgiVt+K+hEZW5yis/NuvbaSLUgsFJVOWnHHOYg0C42k2hRkKKZZUKkdKDdz3bOfcLmxvRGIkN4j//YtjmsjQsrxgS+4PxcgmfEH4U6r5ZP+yUL4GkPHAZS4H6fcdkd1O96PRDnyJcynMbZ9EmbEGhjzpyiaM0mYZ7H/R31+WUNyiaP44vACTVWyLFxvMej4=
